name: cleanconnect-pro-enhanced
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11

  # Scientific Computing Core
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.4.2

  # PyTorch
  - pytorch::pytorch=2.2.2
  - pytorch::cpuonly
  - pytorch::torchvision=0.17.2

  # Development & Testing
  - pytest=8.2.2
  - black=24.4.2
  - jupyter=1.0.0
  - jupyterlab=4.2.1
  - ipython=8.18.1

  # Data Tools
  - beautifulsoup4=4.12.3
  - requests=2.32.3
  - pyyaml=6.0.1

  # Visualization
  - matplotlib=3.8.4
  - plotly=5.22.0

  # Build tools
  - pip

variables:
  PYTHONUNBUFFERED: '1'
